version: "3.7"

services:
  tcp-app:
    build:
      context: .
    ports:
      - "12345"
    volumes:
      - ./:/server
    command: "python tcp_server.py"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tcp-app
    ports:
      - "11111:12345"