version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - "12345"
    volumes:
      - ./:/server

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "11111:12345"